Program Menu_Pilihan;
uses crt;
var

Masukan : integer;
nama,kelamin,kelas,alamat,agama,hobi:string;
nis,nohp:integer;
p,l,pl:integer;
a,b: integer;
huruf:char;
nilai:integer;

begin
clrscr;
writeln('Menu Program');
writeln('Amos W Nauseni');
writeln('1.Program Biodata');
writeln('2.Program Luas Persegi Panjang');
writeln('3.Program kalkulator');
writeln('4.Program konversi nilai huruf');
writeln('5.Program Kelulusan');
write('masukan pilihan anda  :'); readln(masukan);
readln;
end.