Program kalkulator;
uses crt;
var P,L:integer;
begin
      clrscr;
      writeln('Program Luas Persegi Panjang');
      write('masukan nilai penajang=');
      readln(P);
      write('masukan masukan nilai lebar=');
      readln(L);
      writeln('Dik: P= ',P);
      writeln('     L= ',L);
      writeln('Dit: L=?');
      writeln('Rumus: L= P*L');
      writeln('        =',P,' * ',L);
      writeln('        =',P*L);
readln;
end.

